<a href="https://colab.research.google.com/github/ianvogel-glitch/Datascience_mkt/blob/main/Aula_DataScience_Mkt_Ian.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ian Roscoe Bessa Vogel


09/09/2026

Conhecendo os Frameworks e pacotes utilizados em Ciência de Dados _ Introdução ao Python, NumPy e Pandas
Aula prática | Instalação ambiente Python | Exercício prático

(Práticas com Python (Marketing Digital) https://meet.google.com/xao-oeeh-tab) Link da aula prática.

In [2]:
'''
Meu primeiro codigo
'''


#Meu primeiro codigo


print("Meu primeiro codigo")

Meu primeiro codigo

In [3]:
valor_int = 3
valor_float = 1.5
valor_string = "Ola, mundo"
valor_bool = True

print(valor_int)
print(valor_float)
print(valor_string)
print(valor_bool)

3
1.5
Ola, mundo
True

In [4]:
a = 100
b = str(a)
print(b)
print(type(b))

c = 12.0
d = int(c)
print(d)
print(type(d))

100
<class 'str'>
12
<class 'int'>

Aula 2 - 16/09 Manipulação de Dados

Unidade 4

In [ ]:
import pandas as pd

In [5]:
import pandas as pd
cidades = pd.DataFrame(
    [
        ["Paraná", "Londrina", 575377, 1356.00],
        ["São Paulo", "São Carlos", 254484, 1508.00],
        ["Santa Catarina", "Florianópolis", 508826, 1798.00],
        ["Paraná", "Curitiba", 1963726, 2293.00],
        ["São Paulo", "Campinas", 1223237, 1710.00]
    ], columns = ["Estado", "Cidade do Estado","Habitantes", "Salario-Medio"])
cidades

           Estado Cidade do Estado  Habitantes  Salario-Medio
0          Paraná         Londrina      575377         1356.0
1       São Paulo       São Carlos      254484         1508.0
2  Santa Catarina    Florianópolis      508826         1798.0
3          Paraná         Curitiba     1963726         2293.0
4       São Paulo         Campinas     1223237         1710.0

In [6]:
df = pd.read_csv("qualidade_vinho.csv", sep = ",", header=0)
df.head(2)

FileNotFoundError: [Errno 2] No such file or directory: 'qualidade_vinho.csv'

In [7]:
cidades.head(2) # Retorna um novo dataframe com as n primeiras amostras

      Estado Cidade do Estado  Habitantes  Salario-Medio
0     Paraná         Londrina      575377         1356.0
1  São Paulo       São Carlos      254484         1508.0

In [8]:
cidades.tail(2) # Retorna um novo dataframe com as n últimas amostras

      Estado Cidade do Estado  Habitantes  Salario-Medio
3     Paraná         Curitiba     1963726         2293.0
4  São Paulo         Campinas     1223237         1710.0

In [9]:
cidades.shape # Retorna uma tupla com o número de linhas e colunas

(5, 4)

In [10]:
cidades.shape # Retorna uma tupla com o número de linhas e colunas

(5, 4)

In [11]:
cidades.info() # Retorna vazio e imprime na tela as informações gerais do dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Estado            5 non-null      object
 1   Cidade do Estado  5 non-null      object
 2   Habitantes        5 non-null      int64
 3   Salario-Medio     5 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

In [12]:
cidades.columns # Retorna uma lista com o nome de todas as colunas

Index(['Estado', 'Cidade do Estado', 'Habitantes', 'Salario-Medio'], dtype='object')

In [13]:
cidades['Salário-Médio'].describe() # Retorna um objeto DataFrame com as medidas estatísticas para cada coluna

KeyError: 'Salário-Médio'

Tipos de Dados com Pandas

In [14]:
cidades.dtypes
cidades.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Estado            5 non-null      object
 1   Cidade do Estado  5 non-null      object
 2   Habitantes        5 non-null      int64
 3   Salario-Medio     5 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

In [15]:
cidades['Habitantes'] = cidades['Habitantes'].astype('float64')
cidades.dtypes

Estado               object
Cidade do Estado     object
Habitantes          float64
Salario-Medio       float64
dtype: object

In [16]:
cidades['Data'] = ['3-8-2021', '3-9-2021', '3-10-2021', '3-11-2021', '3-12-2021']

cidades['Data'] = pd.to_datetime(cidades['Data'], format='%d-%m-%Y') # Dia, Mês, Ano

cidades

           Estado Cidade do Estado  Habitantes  Salario-Medio       Data
0          Paraná         Londrina    575377.0         1356.0 2021-08-03
1       São Paulo       São Carlos    254484.0         1508.0 2021-09-03
2  Santa Catarina    Florianópolis    508826.0         1798.0 2021-10-03
3          Paraná         Curitiba   1963726.0         2293.0 2021-11-03
4       São Paulo         Campinas   1223237.0         1710.0 2021-12-03

In [17]:
cidades['Data'] = cidades['Data'].dt.strftime('%d-%m-%Y') # Dia, Mês, Ano
cidades # Novo Formato

           Estado Cidade do Estado  Habitantes  Salario-Medio        Data
0          Paraná         Londrina    575377.0         1356.0  03-08-2021
1       São Paulo       São Carlos    254484.0         1508.0  03-09-2021
2  Santa Catarina    Florianópolis    508826.0         1798.0  03-10-2021
3          Paraná         Curitiba   1963726.0         2293.0  03-11-2021
4       São Paulo         Campinas   1223237.0         1710.0  03-12-2021

Renomeando Colunas

In [18]:
cidades.rename(columns={'Habitantes': 'N Habitantes', 'Data': 'Data - Censo'}, inplace=True)
cidades

           Estado Cidade do Estado  N Habitantes  Salario-Medio Data - Censo
0          Paraná         Londrina      575377.0         1356.0   03-08-2021
1       São Paulo       São Carlos      254484.0         1508.0   03-09-2021
2  Santa Catarina    Florianópolis      508826.0         1798.0   03-10-2021
3          Paraná         Curitiba     1963726.0         2293.0   03-11-2021
4       São Paulo         Campinas     1223237.0         1710.0   03-12-2021

Selecionando Linhas e Colunas

In [19]:
cidadesHab = cidades[['N Habitantes', 'Salário-Médio']] # Seleciona as duas colunas com os nomes especificados
cidadesHab

KeyError: "['Salário-Médio'] not in index"

In [20]:
cidades.loc[[1, 2]] # Seleciona as duas linhas com os nomes especificados (note que o "rótulo" de cada linha está presente na forma de números inteiros)

           Estado Cidade do Estado  N Habitantes  Salario-Medio Data - Censo
1       São Paulo       São Carlos      254484.0         1508.0   03-09-2021
2  Santa Catarina    Florianópolis      508826.0         1798.0   03-10-2021

In [21]:
cidades.iloc[1:3] # Seleciona as linhas do dataframe original, referentes ao índice determinado

           Estado Cidade do Estado  N Habitantes  Salario-Medio Data - Censo
1       São Paulo       São Carlos      254484.0         1508.0   03-09-2021
2  Santa Catarina    Florianópolis      508826.0         1798.0   03-10-2021

In [22]:
cidades.iloc[:, 0:2] # Seleciona todas as linhas e as duas primeiras colunas do dataframe original

           Estado Cidade do Estado
0          Paraná         Londrina
1       São Paulo       São Carlos
2  Santa Catarina    Florianópolis
3          Paraná         Curitiba
4       São Paulo         Campinas

In [23]:
cidades.iloc[1:3, :3] # Seleciona as duas primeiras linhas e as três primeiras colunas

           Estado Cidade do Estado  N Habitantes
1       São Paulo       São Carlos      254484.0
2  Santa Catarina    Florianópolis      508826.0

In [24]:
cidades.iloc[:, [1, 3, 0, 2]] # Seleciona todas as linhas e as colunas determinadas

  Cidade do Estado  Salario-Medio          Estado  N Habitantes
0         Londrina         1356.0          Paraná      575377.0
1       São Carlos         1508.0       São Paulo      254484.0
2    Florianópolis         1798.0  Santa Catarina      508826.0
3         Curitiba         2293.0          Paraná     1963726.0
4         Campinas         1710.0       São Paulo     1223237.0

Adicionando e Removendo Colunas

In [25]:
cidades.insert(2, 'Sigla', ['PR', 'SP', 'SC', 'PR', 'SP']) # Adiciona novos dados no índice dois
cidades.insert(2, 'Sigla-Repetida', cidades['Sigla']) # Adiciona uma coluna repetida "Sigla"
cidades

,Estado,Cidade do Estado,Sigla-Repetida,Sigla,N Habitantes,Salario-Medio,Data - Censo
0,Paraná,Londrina,PR,PR,575377.0,1356.0,03-08-2021
1,São Paulo,São Carlos,SP,SP,254484.0,1508.0,03-09-2021
2,Santa Catarina,Florianópolis,SC,SC,508826.0,1798.0,03-10-2021
3,Paraná,Curitiba,PR,PR,1963726.0,2293.0,03-11-2021
4,São Paulo,Campinas,SP,SP,1223237.0,1710.0,03-12-2021

In [26]:
cidades.pop('Sigla-Repetida')

# ou

cidades = cidades.drop(['Sigla-Repetida'], axis=1)
cidades

KeyError: "['Sigla-Repetida'] not found in axis"

Operações Básicas - Consultas

In [27]:
cidades.query('`Salário-Médio` > 1400.0')

UndefinedVariableError: name 'BACKTICK_QUOTED_STRING_Salário_MINUS_Médio' is not defined

In [28]:
cidades.query('Estado == "São Paulo"')

      Estado Cidade do Estado Sigla  N Habitantes  Salario-Medio Data - Censo
1  São Paulo       São Carlos    SP      254484.0         1508.0   03-09-2021
4  São Paulo         Campinas    SP     1223237.0         1710.0   03-12-2021

In [29]:
cidades.query('`N Habitantes` > 500000 and `N Habitantes` < 1300000')

,Estado,Cidade do Estado,Sigla,N Habitantes,Salario-Medio,Data - Censo
0,Paraná,Londrina,PR,575377.0,1356.0,03-08-2021
2,Santa Catarina,Florianópolis,SC,508826.0,1798.0,03-10-2021
4,São Paulo,Campinas,SP,1223237.0,1710.0,03-12-2021

Operações Básicas - Ordenação

In [30]:
cidades_salarios = pd.DataFrame(
    [
        ['Paraná', 'Londrina', 1356.00],
        ['São Paulo', 'São Carlos', 1508.00],
        ['Santa Catarina', 'Florianópolis', 1798.00],
        ['Paraná', 'Curitiba', 2293.00],
        ['São Paulo', 'Campinas', 1710.00]
    ], columns=['Estado', 'Cidade', 'Salário-Médio'])

cidades_salarios

           Estado         Cidade  Salário-Médio
0          Paraná       Londrina         1356.0
1       São Paulo     São Carlos         1508.0
2  Santa Catarina  Florianópolis         1798.0
3          Paraná       Curitiba         2293.0
4       São Paulo       Campinas         1710.0

In [31]:
cidades_pop = pd.DataFrame(
    [
        ['Londrina', 575377],
        ['São Carlos', 254484],
        ['Florianópolis', 508826],
        ['Curitiba', 1963726],
        ['Campinas', 1223237]
    ], columns=['Cidade', 'Habitantes'])

cidades_pop

          Cidade  Habitantes
0       Londrina      575377
1     São Carlos      254484
2  Florianópolis      508826
3       Curitiba     1963726
4       Campinas     1223237

In [32]:
pd.merge(left=cidades_salarios, right=cidades_pop, on="Cidade")

           Estado         Cidade  Salário-Médio  Habitantes
0          Paraná       Londrina         1356.0      575377
1       São Paulo     São Carlos         1508.0      254484
2  Santa Catarina  Florianópolis         1798.0      508826
3          Paraná       Curitiba         2293.0     1963726
4       São Paulo       Campinas         1710.0     1223237

In [33]:
pd.merge(left=cidades_salarios, right=cidades_pop, on="Cidade", how="outer")

           Estado         Cidade  Salário-Médio  Habitantes
0       São Paulo       Campinas         1710.0     1223237
1          Paraná       Curitiba         2293.0     1963726
2  Santa Catarina  Florianópolis         1798.0      508826
3          Paraná       Londrina         1356.0      575377
4       São Paulo     São Carlos         1508.0      254484

In [34]:
cidades_df1 = pd.DataFrame(
    [
        ['Londrina', 575377],
        ['São Carlos', 254484],
        ['Florianópolis', 508826],
    ], columns=['Cidade', 'Habitantes'])

cidades_df1

          Cidade  Habitantes
0       Londrina      575377
1     São Carlos      254484
2  Florianópolis      508826

In [35]:
cidades_df2 = pd.DataFrame(
    [
        ['Curitiba', 1963726],
        ['Campinas', 1223237]
    ], columns=['Cidade', 'Habitantes'])

cidades_df2

     Cidade  Habitantes
0  Curitiba     1963726
1  Campinas     1223237

In [36]:
pd.concat([cidades_df1, cidades_df2], ignore_index=True)

          Cidade  Habitantes
0       Londrina      575377
1     São Carlos      254484
2  Florianópolis      508826
3       Curitiba     1963726
4       Campinas     1223237

Operações Básicas - Salvando DataFrames

In [1]:
cidades.to_csv("my_df.csv")
cidades.to_html("my_df.html")
cidades.to_json("my_df.json")

NameError: name 'cidades' is not defined